### PR TITLE
fix for HsvColorPicker initialColor

### PR DESCRIPTION
**Pull request by tberghuis**

### CODE REVIEW

**Comment by skydoves** [comment]
Hey @tberghuis, thanks for your contribution. Would you elaborate on this PR?

**Comment by tberghuis** [comment]
The picker was selecting the wrong color for initialColor, the angle just needed to be in the negative direction.

I have found other problems like if you place HsvColorPicker in a scrollable column, sliding the picker doesn't work properly. Also picker position gets reset to initialColor on configuration change (screen rotate).

Decided not to use this library for now.

**Comment by skydoves** [comment]
@tberghuis thanks for your explanation and contribution. The scrollable issue was resolved in #29. This PR and many feature improvements will be shipped in the next release very soon. Thanks.

**Comment by tberghuis** [comment]
I think having initialColor and state as part of the controller would be a better design. Would allow keeping Controller in a ViewModel to eliminate configuration change bugs.

**Pull request merged**
